### ISSUE TITLE
Can't install feedb npm package

### ISSUE THREAD

**Issue by mennchen22** [feedbax/ui-user#2]
Hey there, wanted to start your ui frontend but it seems that "api npm package" its not permissiond to install yet

Here's the error log:
in "./ui-user"
```bash
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://npm.pkg.github.com/download/@feedbax/api/1.0.26/e53449d7046269cbda772b1645f1aabfe40604d6042fba9cd9fc538a546b7fc4: Request failed \"401 Unauthorized\"".
```

**Comment by hedwiggggg** [comment]
Hi! Yes & an official manual will be in the Readme sometime.

https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages#installing-a-package

You just need to rename the `__EDIT_ME__.npmrc` to `.npmrc` and insert a personal access token (with the `read:packages` scope)

You can do this here: https://github.com/settings/tokens
